-- ============================================
-- Migration: 0061_embeddings_v2.sql
-- Task: PR-047 F6.1.1-F6.1.2 - Embeddings Schema v2
-- Sprint 8: AI & Vector Search
-- ============================================
-- UPGRADE: Migrate from vector(1536) to vector(3072)
-- NEW: Add variant_id, quality_level, source, lang columns
-- BREAKING: Requires re-embedding all existing data
-- ============================================

-- ============================================
-- 1. SAFETY CHECKS
-- ============================================

DO $$
BEGIN
    -- Verify pgvector extension exists
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
        RAISE EXCEPTION 'pgvector extension not found! Please run 0000_enable_extensions.sql first.';
    END IF;
    
    -- Verify prod_embeddings table exists
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_name = 'prod_embeddings'
    ) THEN
        RAISE EXCEPTION 'prod_embeddings table not found! Please run 0006_vectors_schema.sql first.';
    END IF;
    
    RAISE NOTICE '✅ Pre-migration checks passed';
END $$;

-- ============================================
-- 2. ADD NEW COLUMNS TO prod_embeddings
-- ============================================

-- Add variant_id column (nullable FK to shopify_variants)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'prod_embeddings' AND column_name = 'variant_id'
    ) THEN
        ALTER TABLE prod_embeddings 
            ADD COLUMN variant_id UUID REFERENCES shopify_variants(id) ON DELETE SET NULL;
        RAISE NOTICE '✅ Added variant_id column';
    ELSE
        RAISE NOTICE '⏭️ variant_id column already exists';
    END IF;
END $$;

-- Add quality_level column with CHECK constraint
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'prod_embeddings' AND column_name = 'quality_level'
    ) THEN
        ALTER TABLE prod_embeddings 
            ADD COLUMN quality_level VARCHAR(20) DEFAULT 'bronze'
            CHECK (quality_level IN ('bronze', 'silver', 'golden', 'review_needed'));
        RAISE NOTICE '✅ Added quality_level column';
    ELSE
        RAISE NOTICE '⏭️ quality_level column already exists';
    END IF;
END $$;

-- Add source column
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'prod_embeddings' AND column_name = 'source'
    ) THEN
        ALTER TABLE prod_embeddings 
            ADD COLUMN source VARCHAR(50) DEFAULT 'shopify'
            CHECK (source IN ('shopify', 'vendor', 'ai', 'manual'));
        RAISE NOTICE '✅ Added source column';
    ELSE
        RAISE NOTICE '⏭️ source column already exists';
    END IF;
END $$;

-- Add lang column with default 'ro'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'prod_embeddings' AND column_name = 'lang'
    ) THEN
        ALTER TABLE prod_embeddings 
            ADD COLUMN lang VARCHAR(10) DEFAULT 'ro' NOT NULL;
        RAISE NOTICE '✅ Added lang column';
    ELSE
        RAISE NOTICE '⏭️ lang column already exists';
    END IF;
END $$;

-- Add updated_at column if not exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'prod_embeddings' AND column_name = 'updated_at'
    ) THEN
        ALTER TABLE prod_embeddings 
            ADD COLUMN updated_at TIMESTAMPTZ DEFAULT now();
        RAISE NOTICE '✅ Added updated_at column';
    ELSE
        RAISE NOTICE '⏭️ updated_at column already exists';
    END IF;
END $$;

-- ============================================
-- 3. MIGRATE VECTOR DIMENSION FROM 1536 TO 3072
-- ============================================

-- Step 3.1: Delete existing embeddings (they need to be regenerated)
-- This is a breaking change - old 1536-dim vectors are incompatible
DO $$
DECLARE
    deleted_count INTEGER;
BEGIN
    -- Count existing embeddings
    SELECT COUNT(*) INTO deleted_count FROM prod_embeddings;
    
    IF deleted_count > 0 THEN
        -- Delete old embeddings (they will be regenerated by the backfill job)
        DELETE FROM prod_embeddings;
        RAISE NOTICE '⚠️ Deleted % existing embeddings (incompatible with new 3072 dimensions)', deleted_count;
    ELSE
        RAISE NOTICE '✅ No existing embeddings to delete';
    END IF;
END $$;

-- Step 3.2: Drop existing HNSW index
DROP INDEX IF EXISTS idx_embeddings_vector;
RAISE NOTICE '✅ Dropped old HNSW index';

-- Step 3.3: Alter embedding column to vector(3072)
ALTER TABLE prod_embeddings 
    ALTER COLUMN embedding TYPE vector(3072);
RAISE NOTICE '✅ Changed embedding column to vector(3072)';

-- Step 3.4: Update dimensions default
ALTER TABLE prod_embeddings 
    ALTER COLUMN dimensions SET DEFAULT 3072;
RAISE NOTICE '✅ Updated dimensions default to 3072';

-- ============================================
-- 4. ADD CHECK CONSTRAINT FOR DIMENSIONS
-- ============================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'chk_prod_embeddings_dims' AND conrelid = 'prod_embeddings'::regclass
    ) THEN
        ALTER TABLE prod_embeddings 
            ADD CONSTRAINT chk_prod_embeddings_dims 
            CHECK (dimensions = 3072);
        RAISE NOTICE '✅ Added CHECK constraint for dimensions = 3072';
    ELSE
        RAISE NOTICE '⏭️ CHECK constraint already exists';
    END IF;
END $$;

-- ============================================
-- 5. CREATE NEW INDEXES
-- ============================================

-- Recreate HNSW index for vector(3072)
-- Using m=32, ef_construction=128 for >1M items
CREATE INDEX idx_embeddings_vector ON prod_embeddings 
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 32, ef_construction = 128);
RAISE NOTICE '✅ Created new HNSW index for vector(3072)';

-- Index for quality_level and updated_at (for incremental processing)
CREATE INDEX IF NOT EXISTS idx_embeddings_quality_updated 
    ON prod_embeddings(quality_level, updated_at DESC);
RAISE NOTICE '✅ Created quality_level + updated_at index';

-- Composite index for product + variant lookups
CREATE INDEX IF NOT EXISTS idx_embeddings_product_variant 
    ON prod_embeddings(product_id, variant_id NULLS FIRST);
RAISE NOTICE '✅ Created product_id + variant_id index';

-- Index for lang filtering
CREATE INDEX IF NOT EXISTS idx_embeddings_lang 
    ON prod_embeddings(lang);
RAISE NOTICE '✅ Created lang index';

-- Index for source filtering
CREATE INDEX IF NOT EXISTS idx_embeddings_source 
    ON prod_embeddings(source);
RAISE NOTICE '✅ Created source index';

-- ============================================
-- 6. UPDATE UNIQUE CONSTRAINT
-- ============================================

-- Drop old unique constraint if exists
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'prod_embeddings_product_id_embedding_type_key'
    ) THEN
        ALTER TABLE prod_embeddings 
            DROP CONSTRAINT prod_embeddings_product_id_embedding_type_key;
        RAISE NOTICE '✅ Dropped old unique constraint';
    END IF;
END $$;

-- Create new unique constraint including variant_id and quality_level
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'uq_prod_embeddings_product_variant_quality'
    ) THEN
        ALTER TABLE prod_embeddings 
            ADD CONSTRAINT uq_prod_embeddings_product_variant_quality 
            UNIQUE (product_id, variant_id, quality_level, embedding_type);
        RAISE NOTICE '✅ Created new unique constraint';
    END IF;
END $$;

-- ============================================
-- 7. RECREATE HELPER FUNCTIONS FOR vector(3072)
-- ============================================

-- Drop old function signature
DROP FUNCTION IF EXISTS find_similar_products(vector(1536), float, int);

-- Create new function with vector(3072)
CREATE OR REPLACE FUNCTION find_similar_products(
    query_embedding vector(3072),
    similarity_threshold float DEFAULT 0.95,
    max_results int DEFAULT 10
)
RETURNS TABLE (
    product_id uuid,
    variant_id uuid,
    embedding_type varchar(50),
    quality_level varchar(20),
    similarity float
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        e.product_id,
        e.variant_id,
        e.embedding_type,
        e.quality_level,
        (1 - (e.embedding <=> query_embedding))::float as similarity
    FROM prod_embeddings e
    WHERE e.embedding_type = 'combined'
        AND (e.embedding <=> query_embedding) < (1 - similarity_threshold)
    ORDER BY e.embedding <=> query_embedding
    LIMIT max_results;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION find_similar_products(vector(3072), float, int) IS 
    'Find similar products using cosine similarity on 3072-dim embeddings';

RAISE NOTICE '✅ Created find_similar_products function for vector(3072)';

-- ============================================
-- 8. UPDATE shop_product_embeddings TABLE
-- ============================================

-- Similar updates for shop_product_embeddings (per-tenant table)

-- Delete existing shop embeddings (incompatible dimensions)
DO $$
DECLARE
    deleted_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO deleted_count FROM shop_product_embeddings;
    
    IF deleted_count > 0 THEN
        DELETE FROM shop_product_embeddings;
        RAISE NOTICE '⚠️ Deleted % existing shop embeddings', deleted_count;
    END IF;
END $$;

-- Drop old HNSW index
DROP INDEX IF EXISTS idx_shop_embeddings_vector;

-- Alter embedding column
ALTER TABLE shop_product_embeddings 
    ALTER COLUMN embedding TYPE vector(3072);

-- Update dimensions default
ALTER TABLE shop_product_embeddings 
    ALTER COLUMN dimensions SET DEFAULT 3072;

-- Add quality_level column if not exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'shop_product_embeddings' AND column_name = 'quality_level'
    ) THEN
        ALTER TABLE shop_product_embeddings 
            ADD COLUMN quality_level VARCHAR(20) DEFAULT 'bronze'
            CHECK (quality_level IN ('bronze', 'silver', 'golden', 'review_needed'));
    END IF;
END $$;

-- Add source column if not exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'shop_product_embeddings' AND column_name = 'source'
    ) THEN
        ALTER TABLE shop_product_embeddings 
            ADD COLUMN source VARCHAR(50) DEFAULT 'shopify';
    END IF;
END $$;

-- Add lang column if not exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'shop_product_embeddings' AND column_name = 'lang'
    ) THEN
        ALTER TABLE shop_product_embeddings 
            ADD COLUMN lang VARCHAR(10) DEFAULT 'ro' NOT NULL;
    END IF;
END $$;

-- Recreate HNSW index
CREATE INDEX idx_shop_embeddings_vector ON shop_product_embeddings 
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 24, ef_construction = 128);

RAISE NOTICE '✅ Updated shop_product_embeddings to vector(3072)';

-- ============================================
-- 9. UPDATE find_similar_shop_products FUNCTION
-- ============================================

DROP FUNCTION IF EXISTS find_similar_shop_products(uuid, vector(1536), float, int);

CREATE OR REPLACE FUNCTION find_similar_shop_products(
    p_shop_id uuid,
    query_embedding vector(3072),
    similarity_threshold float DEFAULT 0.9,
    max_results int DEFAULT 20
)
RETURNS TABLE (
    product_id uuid,
    embedding_type varchar(50),
    quality_level varchar(20),
    similarity float
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        e.product_id,
        e.embedding_type,
        e.quality_level,
        (1 - (e.embedding <=> query_embedding))::float as similarity
    FROM shop_product_embeddings e
    WHERE e.shop_id = p_shop_id
        AND e.status = 'ready'
        AND (e.embedding <=> query_embedding) < (1 - similarity_threshold)
    ORDER BY e.embedding <=> query_embedding
    LIMIT max_results;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION find_similar_shop_products(uuid, vector(3072), float, int) IS 
    'Find similar shop products using cosine similarity on 3072-dim embeddings (RLS-aware)';

RAISE NOTICE '✅ Created find_similar_shop_products function for vector(3072)';

-- ============================================
-- 10. UPDATE prod_attr_definitions TABLE
-- ============================================

-- Delete existing attribute embeddings
DELETE FROM prod_attr_definitions WHERE embedding IS NOT NULL;

-- Drop old HNSW index
DROP INDEX IF EXISTS idx_attr_embedding;

-- Alter embedding column
ALTER TABLE prod_attr_definitions 
    ALTER COLUMN embedding TYPE vector(3072);

-- Recreate HNSW index
CREATE INDEX idx_attr_embedding ON prod_attr_definitions 
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

RAISE NOTICE '✅ Updated prod_attr_definitions to vector(3072)';

-- ============================================
-- 11. VERIFICATION
-- ============================================

DO $$
DECLARE
    col_check RECORD;
    idx_count INTEGER;
    func_count INTEGER;
BEGIN
    -- Check new columns exist
    SELECT 
        (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'prod_embeddings' AND column_name = 'variant_id') AS has_variant_id,
        (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'prod_embeddings' AND column_name = 'quality_level') AS has_quality_level,
        (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'prod_embeddings' AND column_name = 'source') AS has_source,
        (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'prod_embeddings' AND column_name = 'lang') AS has_lang
    INTO col_check;
    
    IF col_check.has_variant_id = 1 AND col_check.has_quality_level = 1 
       AND col_check.has_source = 1 AND col_check.has_lang = 1 THEN
        RAISE NOTICE '✅ All new columns verified';
    ELSE
        RAISE WARNING '⚠️ Some columns missing';
    END IF;
    
    -- Check HNSW indexes
    SELECT COUNT(*) INTO idx_count
    FROM pg_indexes
    WHERE indexdef LIKE '%hnsw%' AND indexdef LIKE '%3072%';
    
    IF idx_count >= 3 THEN
        RAISE NOTICE '✅ HNSW indexes verified: % indexes with vector(3072)', idx_count;
    ELSE
        RAISE WARNING '⚠️ Expected 3+ HNSW indexes, found %', idx_count;
    END IF;
    
    -- Check helper functions
    SELECT COUNT(*) INTO func_count
    FROM pg_proc p
    JOIN pg_namespace n ON p.pronamespace = n.oid
    WHERE n.nspname = 'public' 
        AND p.proname IN ('find_similar_products', 'find_similar_shop_products');
    
    IF func_count = 2 THEN
        RAISE NOTICE '✅ Helper functions verified';
    ELSE
        RAISE WARNING '⚠️ Expected 2 helper functions, found %', func_count;
    END IF;
    
    RAISE NOTICE '';
    RAISE NOTICE '============================================';
    RAISE NOTICE '✅ Migration 0061_embeddings_v2.sql completed';
    RAISE NOTICE '============================================';
    RAISE NOTICE 'IMPORTANT: All embeddings have been deleted.';
    RAISE NOTICE 'Run the backfill job to regenerate embeddings with 3072 dimensions.';
    RAISE NOTICE '============================================';
END $$;
