-- Migration: 0113_metafield_definition_ai.sql
-- Purpose: AI-generated metafield definitions registry (global per shop) +
--          schema enrichment for pim_taxonomy_metafield_schema +
--          new pending change type for metafield definition sync

-- ============================================================
-- 1. Registru global de metafield definitions Shopify per shop
-- ============================================================
CREATE TABLE IF NOT EXISTS shopify_metafield_definitions (
  id                          UUID PRIMARY KEY DEFAULT uuidv7(),
  shop_id                     UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  namespace                   VARCHAR(100) NOT NULL DEFAULT 'custom',
  key                         VARCHAR(64) NOT NULL,
  shopify_type                VARCHAR(50) NOT NULL,
  name                        VARCHAR(200) NOT NULL,
  description                 TEXT,
  owner_type                  VARCHAR(20) NOT NULL DEFAULT 'PRODUCT',
  use_as_filter               BOOLEAN NOT NULL DEFAULT true,
  shopify_definition_gid      VARCHAR(200),
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced_at                   TIMESTAMPTZ,
  CONSTRAINT chk_metafield_def_owner_type
    CHECK (owner_type IN ('PRODUCT', 'VARIANT', 'COLLECTION')),
  CONSTRAINT chk_metafield_def_key
    CHECK (key ~ '^[a-z][a-z0-9_]{1,63}$'),
  UNIQUE (shop_id, namespace, key, owner_type)
);

CREATE INDEX IF NOT EXISTS idx_metafield_defs_shop
  ON shopify_metafield_definitions (shop_id);

CREATE INDEX IF NOT EXISTS idx_metafield_defs_shop_gid
  ON shopify_metafield_definitions (shop_id, shopify_definition_gid)
  WHERE shopify_definition_gid IS NOT NULL;

ALTER TABLE shopify_metafield_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE shopify_metafield_definitions FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation_shopify_metafield_definitions
  ON shopify_metafield_definitions
  USING (
    shop_id = COALESCE(
      NULLIF(current_setting('app.current_shop_id', true), '')::uuid,
      '00000000-0000-0000-0000-000000000000'::uuid
    )
  )
  WITH CHECK (
    shop_id = COALESCE(
      NULLIF(current_setting('app.current_shop_id', true), '')::uuid,
      '00000000-0000-0000-0000-000000000000'::uuid
    )
  );

ALTER TABLE shopify_metafield_definitions OWNER TO neanelu_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON shopify_metafield_definitions TO neanelu_app;

COMMENT ON TABLE shopify_metafield_definitions IS
  'Global registry of Shopify product metafield definitions per shop. '
  'Tracks which definitions have been created in Shopify to prevent duplicates (max 128 per shop).';

-- ============================================================
-- 2. Enrichment coloane pe pim_taxonomy_metafield_schema
--    (tabelul este global - fara shop_id, by design)
-- ============================================================
ALTER TABLE pim_taxonomy_metafield_schema
  ADD COLUMN IF NOT EXISTS ai_generated    BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS display_name_en VARCHAR(200),
  ADD COLUMN IF NOT EXISTS description     TEXT;

COMMENT ON COLUMN pim_taxonomy_metafield_schema.ai_generated IS
  'True if this schema entry was generated by AI (brainstorm multi-agent)';
COMMENT ON COLUMN pim_taxonomy_metafield_schema.display_name_en IS
  'English display name for the attribute (AI-generated or manual)';
COMMENT ON COLUMN pim_taxonomy_metafield_schema.description IS
  'Human-readable description of what this attribute measures';

-- ============================================================
-- 3. Actualizare CHECK constraints pe collection_pending_changes
-- ============================================================

-- Adaugă metafield_definition_create la tipuri permise
ALTER TABLE collection_pending_changes
  DROP CONSTRAINT IF EXISTS chk_collection_pending_changes_type;

ALTER TABLE collection_pending_changes
  ADD CONSTRAINT chk_collection_pending_changes_type
    CHECK (change_type IN (
      'field_update',
      'taxonomy_assign',
      'taxonomy_unassign',
      'menu_assign',
      'product_dissociate',
      'metafield_definition_create'
    ));

-- Adaugă ai_metafield la surse permise
ALTER TABLE collection_pending_changes
  DROP CONSTRAINT IF EXISTS chk_collection_pending_changes_source;

ALTER TABLE collection_pending_changes
  ADD CONSTRAINT chk_collection_pending_changes_source
    CHECK (source IN (
      'manual',
      'ai_generate',
      'ai_translate',
      'ai_taxonomy',
      'ai_menu',
      'ai_metafield',
      'sync'
    ));

-- Metadata non-empty pentru metafield_definition_create
ALTER TABLE collection_pending_changes
  ADD CONSTRAINT chk_collection_pending_changes_metafield_def
    CHECK (
      change_type != 'metafield_definition_create'
      OR metadata <> '{}'::jsonb
    );
